-- Painel administrativo EnergyInvest
-- Aplicado na Supabase em 2026-09-22.
-- O banco em produção já contém estas funções. Este arquivo documenta os recursos
-- necessários para reinstalações/futuros ambientes.

-- Funções instaladas:
-- public.admin_dashboard_snapshot()
-- public.admin_update_profile(uuid,text,text)
-- public.admin_adjust_wallet(uuid,numeric,text)
-- public.admin_set_user_enabled(uuid,boolean)
-- public.admin_update_referral_settings(boolean,numeric,numeric)
-- public.admin_delete_project(uuid)
-- public.admin_process_due_credits()
-- public.admin_reconcile_syncpay()
--
-- Todas validam private.is_admin() e operações mutáveis registram auditoria.
-- O histórico financeiro (depósitos, transações e créditos concluídos) é mantido
-- como registro de auditoria; o dashboard oferece as ações operacionais seguras
-- em vez de exclusão arbitrária desses lançamentos.
